vich_uploader:
    db_driver: orm

    mappings:
        project_images:
            uri_prefix: '%project_images%'
            upload_destination: '%kernel.project_dir%/public%project_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer